[main]
gpgcheck=1
installonly_limit=3
clean_requirements_on_remove=True
best=False
skip_if_unavailable=True
localpkg_gpgcheck=True

# This allows us to check for updates without remounting RW
cachedir=/run/dnf/cache

# ==================================
# PRODUCTION REPOSITORY
# ==================================
[higeco]
name=higeco
baseurl=https://rpm.higeco.com/hsc

# ==================================
# BETA REPOSITORY! NOT TO BE USED!
# ==================================
# [higeco-beta]
# name=higeco-beta
# baseurl=https://rpm.higeco.com/hsc-beta
